# Editor configuration
# Choose editor backend: "tui-textarea" (more backends can be added in the future)
[editor]
backend = "tui-textarea"

# Database connections
[[connections]]
host = "localhost"
port = 5432
username = "postgres"
password = "secret5"
database = "postgres"
sslmode = "prefer"

[[connections]]
host = "localhost"
port = 64333
username = "join_root"
password = "faceBegunIllFarmer"
database = "komodo"
sslmode = "disable"

[[connections]]
host = "localhost"
port = 64333
username = "postgres"
password = "secret5"
database = "postgres"
sslmode = "prefer"
