# Editor configuration
# Choose editor backend: "tui-textarea" or "zep"
[editor]
backend = "zep"

# Database connections
[[connections]]
host = "localhost"
port = 5432
username = "postgres"
password = "secret5"
database = "postgres"
sslmode = "prefer"

[[connections]]
host = "localhost"
port = 64333
username = "join_root"
password = "faceBegunIllFarmer"
database = "komodo"
sslmode = "disable"

[[connections]]
host = "localhost"
port = 64333
username = "postgres"
password = "secret5"
database = "postgres"
sslmode = "prefer"
