[build]
# Use a stable target directory to avoid Nix-related rebuilds
target-dir = "target"

# Number of parallel jobs, defaults to # of CPUs
jobs = 8

# Enable incremental compilation
incremental = true

[env]
# Force Cargo to use mtime-based change detection instead of content-based
# This helps with Nix environments where timestamps can be problematic
CARGO_CACHE_RUSTC_INFO = "1"

# [target.aarch64-unknown-linux-gnu]
# Temporarily disable target-specific flags to avoid linker issues

[profile.dev]
# Faster builds with reasonable runtime performance
opt-level = 0
debug = 1  # Line info only, faster builds
lto = false
incremental = true
overflow-checks = true

[profile.dev.package."*"]
# Optimize dependencies even in debug mode
opt-level = 2
debug = false

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true

